### ISSUE TITLE
Documentation: bmap-tools

### ISSUE THREAD

**Issue by someburner** [FuturePilot/Pi2buntu#14]
Just a heads up that the Ubuntu repo has bmaptools v2.x which does not work with your .bmap file. Need to add "deb http://download.tizen.org/tools/latest-release/Ubuntu_14.04 /" to sources.list, run apt-get update, and then apt-get install "bmap-tools".

**Comment by FuturePilot** [comment]
Thanks! I didn't realize there was a break in compatibility with the new 3.x bmap-tools.

**Comment by FuturePilot** [comment]
I have updated the release notes with the steps for Ubuntu 14.04 users. This will be included in the release notes for each new release from now on.
